name: Download and Convert

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 1 1 *"
  
  
permissions:
  contents: write

jobs:

  get:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - id: start_build
      run: |
        bash build.sh
    - name: Push to release
      uses: softprops/action-gh-release@v3
      with:
          tag_name: ${{ steps.start_build.outputs.RELEASE }}
          name: ${{ steps.start_build.outputs.RELEASE }}
          files: |
            cacert.zip
            cacert.iso
            cacert.pem
          preserve_order: true
          make_latest: true
env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
